# config.yml
nginx:
  domain: "npm.ganjagaming.de"
logfiles:
  - path: /data/npm/logs/fallback_access.log
    proxy_type: npm
  - path: /data/npm/logs/fallback_error.log
    proxy_type: npm

parse_all_logs: true

# Security and default admin settings
secret_key: "S3cUr3K3y!@#123"
security_password_salt: "S3cUr3S@lt!@#123"
default_admin_email: "admin@example.com"
default_admin_password: "changeme"
